server:
  port: 80

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/webflux_security
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/webflux_security
    locations: classpath:db/migration
    user: postgres
    password: postgres

jwt:
  password:
    encoder:
      secret: sE6mKmQZNaqD6FugJGPFp389ct9P7vxZaJRWd96kYKFKxUvnZtPGcjLsDPKQbrXe
      iteration: 64
      keyLength: 256

    secret: 5pfwadgmn0ywg7f2de1qfsxmayt8ojsbsdta1ul9tcdwae3qhn4q3144xxycxco0
    expiration: 3600
    issuer: serviceWebflux
